# Bridge Configuration File

[api]
infura_api_key = "api_key"
max_retries = 3
retry_delay = 5

[delay]
default_delay = 5

[bridge]
gas_multiplier = 1.2

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"